version: '3'

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./mongodb_data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  server:
    image: stevepacker/nodejs-supervisor:latest
    volumes:
      - ./server_src:/app
    depends_on:
      - mongo
    ports:
      - "10066:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  react:
    image: node:10.14-alpine
    volumes:
      - ./react_src:/app
    working_dir: /app
    depends_on:
      - mongo
      - server
    command: ["npm", "run", "start"]
    ports:
      - "10030:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


